### PR TITLE
feat: Allow `log(label, value)` & print labels in C witness generator

### PR DESCRIPTION
**Pull request by phated**
Fixes https://github.com/iden3/circom/issues/82

This PR adds `log("foo", 1)` syntax to the circom language. The label is then printed when generating a witness with the C++ witness generator. It is very hard to add these labels to the wasm generator, so the label is discarded and only the value is printed when generating with the witness in wasm.

This feature is a huge quality-of-life improvement for large circuit authors, like @yi-sun and other @0xPARC members.

### CODE REVIEW

**Comment by yi-sun** [comment]
I'd like to strongly endorse this feature and echo that it would substantially help my dev workflow!

**Comment by alrubio** [comment]
I don't like to merge it if it only works for C. Most developers use the wasm code and they would be confused by the new log instruction. I think adding it to wasm is not that difficult, we can add it soon.

**Comment by calvbore** [comment]
I would also like to strongly endorse this, huge quality of life feature!

**Comment by jtguibas** [comment]
I support this feature with all my heart

**Comment by antimatter15** [comment]
I don't know if this is a good way to do it, but I took a stab at implementing it [for wasm here](https://github.com/antimatter15/circom/commit/29d3f1930df9f4c31db9391ff0b2670732115d9f#diff-ea9114c2034d2b4451f36f2055c0900885033650a2b14da6ebde130de97c3433R55)

**Pull request merged**
