### PR TITLE
macos support for cpp backend;  use template to generate makefile

### PR DESCRIPTION
**Pull request by lispc**

### CODE REVIEW

**Review by alxkzmn — COMMENTED** [review]
I hope that this gets merged ASAP. Thanks a lot! Spent an hour trying to fix it on Mac.

**Review by calvinchengx — APPROVED** [review]
I have confirmed that this patch works for macOS.

macOS user should install system dependencies via

```bash
brew install nlohmann-json gmp nasm
```

**Comment by alrubio** [comment]
> I have confirmed that this patch works for macOS.
> 
> macOS user should install system dependencies via
> 
> ```shell
> brew install nlohmann-json gmp nasm
> ```

I guess you have tried on a Mac with x86_64, but not on a Mac with M1. Right?

**Comment by calvinchengx** [comment]
Yes.

www.calvinx.com ( http://www.calvinx.com )
Stalk me! @ www.twitter.com/calvinchengx ( http://www.twitter.com/calvinchengx )

**Review by alxkzmn — APPROVED** [review]

**Comment by alrubio** [comment]
Thanks for the proposal.
We will merge the PR if you change the last line of the code_producers/src/c_elements/makefile to 

	$(CC) -o {{run_name}} *.o -lgmp {{#if has_parallelism}}-pthread{{/if}}

To keep the same behavior as now.
I've tried to do it myself but I can't edit.
Best
Albert

**Comment by lispc** [comment]
@alrubio I have updated it and merged main branch

**Comment by alrubio** [comment]
Thanks.

**Pull request merged**
